camera:
  active_camera: frontview

  names:
    - frontview
    - birdview
    - agentview
    - sideview
    - robot0_robotview
    - robot0_eye_in_hand

  resolution:
    width: 256
    height: 256

  observation:
    use_camera_obs: false
    use_depth: false
    use_segmentation: false

  rendering:
    has_renderer: true #NOTE - Change before training
    has_offscreen_renderer: false
    render_camera: frontview

  pose_randomization:
    enabled: false
    sample_every_reset: false

    position:
      x_range: [-0.0, 0.0]
      y_range: [-0.0, 0.0]
      z_range: [-0.0, 0.0]

    orientation:
      roll_range: [-0.0, 0.0]
      pitch_range: [-0.0, 0.0]
      yaw_range: [-0.0, 0.0]

  save:
    save_rgb: true
    save_depth: false
    save_intrinsics: false
    save_extrinsics: false